apiVersion: v1

kind: Service

metadata: 
  name: servico-intelipost-usuario

spec: 
  type: LoadBalancer
  ports: 
  - protocol: TCP
    port: 16001
    targetPort: 30009
  selector: 
    app: intelipost-usuario
  externalIPs:
  - 192.168.99.100
